"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/app/theme/theme";
import { CacheProvider } from "@emotion/react";
import createCache from "@emotion/cache";
import rtlPlugin from "stylis-plugin-rtl";
import { prefixer } from "stylis";
import BaseNavbar from "./components/BaseNavbar";
import { Box, Container } from "@mui/material";
import { Provider } from "react-redux";
import { store } from "./redux/store";

const BYekan = localFont({
  src: "./assets/fonts/BYekan/BYekan.ttf",
  variable: "--BYekan",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const cacheRtl = createCache({
  key: "muirtl",
  stylisPlugins: [prefixer, rtlPlugin],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${BYekan.variable}`}>
        <CacheProvider value={cacheRtl}>
          <Provider store={store}>
            <BaseNavbar />
            <Box sx={{ bgcolor: "#cfe8fc", minHeight: "100vh" }}>
              <ThemeProvider theme={theme}>{children}</ThemeProvider>
            </Box>
          </Provider>
        </CacheProvider>
      </body>
    </html>
  );
}
